[tool.pytest.ini_options]
testpaths = [ "tests" ]

[tool.yapf]
column_limit = 100
dedent_closing_brackets = true
indent_dictionary_value = true
spaces_around_default_or_named_assign = false
split_arguments_when_comma_terminated = true
